// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnhrqzhfgpljoodsoyac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaHJxemhmZ3Bsam9vZHNveWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTI2MjAsImV4cCI6MjA3MDY2ODYyMH0.xY_hok-KtxD-k3zSQj4Rc5nDiqBwjVmmGXSIATs0nUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});